version: '3.9'

services:
  redis:
    container_name: redis_tennis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  web:
    build: .
    ports:
      - "5000:5000"
